### ISSUE TITLE
[setup] Create a FastAPI Project

### ISSUE THREAD

**Issue by Phi1lS** [COSC381-2023Fall/final-project-Phi1lS#1]
This issue is to setup the initial project. So we don't have a user story for this issue.

**Tasks**
- [x]  Create a FastAPI project
- [x] Add one HelloWorld API method
- [x] Add a README file that describes how to run this FastAPI project
- [x] Set up testing with coverage and mocker
- [x] Set up GitHub actions for automatic testing

**Acceptance Criteria**
- [x] Have a proper gitignore
- [x] Have a proper requirements.txt
- [x] No unnecessary files included in the project
- [x] Following the README's instruction, others can start this project
- [x] For every push to a branch, do testing to see if the push break any tests
