### ISSUE TITLE
[feature] Find movie commentary/reviews through YouTube API

### ISSUE THREAD

**Issue by Phi1lS** [COSC381-2023Fall/final-project-Phi1lS#4]
**User story**
As someone who loves watching movies and movie reviews, I would like to find more reviews and commentaries through YouTube Data API so that I can get others' opinions on the movie.

- Persona: someone who loves watching movies and movie reviews
- Feature: find movie reviews and commentaries
- Business value: the user can get others' opinions on the movie

**Tasks**
- [x] Set up the YouTube API key in the config.py
- [x] Write a method for searching the movie reviews/commentaries (not an API method). The input should be a movie title, and the output should be a list of 10 movie reviews and commentaries about that movie. (There is no standard/perfect solution to it. Use the best method that you can think of to get the review/commentary videos). (Reference to YouTube Data API: https://developers.google.com/youtube/v3/docs/search/list)
- [x] Add tests for the above method (make sure every statement is tested)
- [x] If needed, update README.md for instructions on how to test the new method
- [x] Write an API method in the FastAPI app. The route should be: `/movie_reviews/{movie_name}`. The API method should return a list of 10 review videos. The data structure of each review video is listed below:
    - `id`: str — This should be the video id from youtube.
    - `title`: str
    - `description`: str
- [x] Add tests for the new API method (make sure every statement is tested)

**Acceptance Criteria**
- The GitHub actions should also work for the new tests
- No unnecessary files included in the project
- Following the README's instruction, others can start this app, and run the tests
- The `requirements.txt` is up to date
- The API `/movie_reviews/{movie_name}` should return a list of ten review videos
- The tests cover all the statements
