### ISSUE TITLE
Get reviews in a different language not properly translating proper nouns

### ISSUE THREAD

**Issue by Phi1lS** [COSC381-2023Fall/final-project-Phi1lS#9]
Our "Get reviews in a different language" method is not translating the search results for "harry potter". We believe that this is because our "search_movie_reviews_in_language" method is not translating the word "review" on line 66 of youtube.py

**Tasks**
- [x] Fix "search_movie_reviews_in_language" to return desired results of videos in a different language without any hitches
- [x] Edit README file to remove part telling user that translating proper nouns does not work

**Acceptance Criteria**
- [x] Translating search term works as intended
- [x] README is updated to remove part informing users of our issue translating proper nouns
